--- 
artifacts: 
  discard-paths: true
  files: 
    - target/messageUtil-1.0.jar
  secondary-artifacts: 
    artifact1: 
      discard-paths: true
      files: 
        - target/artifact-1.0.jar
    artifact2: 
      discard-paths: true
      files: 
        - target/artifact-2.0.jar
cache: 
  paths: 
    - cp ./settings.xml /root/.m2/settings.xml
env: 
  variables: 
    JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
phases: 
  install: 
    commands: 
      - "echo Entered the install phase..."
      - "apt-get update -y"
      - "apt-get install -y maven"
    finally: 
      - "echo This always runs even if the update or install command fails"
  post_build: 
    commands: 
      - "echo Entered the post_build phase..."
      - "echo Build completed on `date`"
  pre_build: 
    build: ~
    commands: 
      - "echo Entered the build phase..."
      - "echo Build started on `date`"
      - "mvn install"
    finally: 
      - "echo This always runs even if the install command fails"
    reports:
    arn:aws:codebuild:Asia Pacific (Mumbai):862112193817:report-groupreport-group-ezaz-1 files:- "**/*" base-directory:'target/tests/reports' discard-paths:no:
    files:- 'cucumber/target/cucumber-tests.xml':
    file-format:CucumberJson:
version: 0.2
